export const Projects = [
  {
    name: "E-Commerce",
    pic: "pic",
    techstack: {
      react: true,
      nextjs: true,
      chakra: true,
      firebase: true,
      stripe: true,
      tailwind: false,
      sanity: false,
    },
  },
  {
    name: "AI Logo Generator",
    pic: "pic",
    techstack: {
      react: true,
      nextjs: true,
      chakra: false,
      firebase: false,
      stripe: false,
      tailwind: true,
      sanity: false,
    },
  },
  {
    name: "My Portfolio",
    pic: "pic",
    techstack: {
      react: true,
      nextjs: true,
      chakra: false,
      firebase: false,
      stripe: false,
      tailwind: true,
      sanity: false,
    },
  },
  {
    name: "Decentralized Crowd Funding",
    pic: "pic",
    techstack: {
      react: true,
      nextjs: true,
      chakra: false,
      firebase: false,
      stripe: false,
      tailwind: true,
      sanity: false,
    },
  },
  {
    name: "Chat App",
    pic: "pic",
    techstack: {
      react: true,
      nextjs: true,
      chakra: false,
      firebase: false,
      stripe: false,
      tailwind: true,
      sanity: false,
    },
  },
];
