const Asset = () => {
  return (
    <svg
      viewBox="0 0 710 711"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="w-0 h-0 asset"
    >
      <defs>
        <linearGradient id="gradient" x1="0%" y1="0%" x2="100%" y2="0%">
          <stop offset="0%" stopColor="#FF0000" stopOpacity="0.2" />
          <stop offset="50%" stopColor="#FFFF00" stopOpacity="0.2" />
          <stop offset="100%" stopColor="#00FF00" stopOpacity="0.2" />
        </linearGradient>
      </defs>
      <clipPath id="clip">
        <rect
          width="24.1%"
          height="24.1%"
          rx="4.2%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="15.1%"
          y="30.5%"
          width="24.1%"
          height="24.1%"
          rx="4.2%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="75.9%"
          width="24.1%"
          height="24.1%"
          rx="4.2%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="30.3%"
          y="60.3%"
          width="24.1%"
          height="24.1%"
          rx="4.2%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="60.7%"
          y="45.4%"
          width="24.1%"
          height="24.1%"
          rx="4.2%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="75.9%"
          y="75.8%"
          width="24.1%"
          height="24.1%"
          rx="4.2%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          y="75.8%"
          width="24.1%"
          height="24.1%"
          rx="4.2%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="45.5%"
          y="15.2%"
          width="24.1%"
          height="24.1%"
          rx="4.2%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          y="45.4%"
          width="9.9%"
          height="24.1%"
          rx="1.4%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="90%"
          y="30.5%"
          width="9.9%"
          height="24.1%"
          rx="1.4%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="69.6%"
          y="90.1%"
          width="9.9%"
          height="24.1%"
          rx="1.4%"
          transform="rotate(89.8183 493.999 640)"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="54.4%"
          width="9.9%"
          height="24.1%"
          rx="1.4%"
          transform="rotate(89.8183 385.999 0)"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="73.8%"
          y="30.4%"
          width="12.1%"
          height="12.1%"
          rx="3.1%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="88%"
          y="59.1%"
          width="12.1%"
          height="12.1%"
          rx="3.1%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="28.7%"
          y="87.9%"
          width="12.1%"
          height="12.1%"
          rx="3.1%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="59.2%"
          width="12.1%"
          height="12.1%"
          rx="3.1%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="15.1%"
          y="59.1%"
          width="12.1%"
          height="12.1%"
          rx="3.1%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          y="28.7%"
          width="12.1%"
          height="12.1%"
          rx="3.1%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="28.7%"
          y="14.2%"
          width="12.1%"
          height="12.1%"
          rx="3.1%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="44%"
          y="43.7%"
          width="12.1%"
          height="12.1%"
          rx="3.1%"
          fill="#D9D9D9"
          className="rect"
        />
        <rect
          x="59.2%"
          y="73.7%"
          width="12.1%"
          height="12.1%"
          rx="3.1%"
          fill="#D9D9D9"
          className="rect"
        />
      </clipPath>
    </svg>
  );
};

export default Asset;
